import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ClientComponent from './_components/client-component';
import ServerComponentNavigation from './_components/server-component-navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	await new Promise(resolve => {
		setTimeout(resolve, 1000);
	});

	return (
		<html lang="en">
			<body className={inter.className}>
				<ClientComponent>
					<ServerComponentNavigation />

					{children}
				</ClientComponent>
			</body>
		</html>
	);
}
